# frozen_string_literal: true

require 'rails_helper'

# This spec was generated by rspec-rails when you ran the scaffold generator.
# It demonstrates how one might use RSpec to test the controller code that
# was generated by Rails when you ran the scaffold generator.
#
# It assumes that the implementation code is generated by the rails scaffold
# generator. If you are using any extension libraries to generate different
# controller code, this generated spec may or may not pass.
#
# It only uses APIs available in rails and/or rspec-rails. There are a number
# of tools you can use to make these specs even more expressive, but we're
# sticking to rails and rspec-rails APIs to keep things simple and stable.

RSpec.describe '/readers', type: :request do
  # This should return the minimal set of attributes required to create a valid
  # Reader. As you add validations to Reader, be sure to
  # adjust the attributes here as well.
  let(:valid_attributes) do
    skip('Add a hash of attributes valid for your model')
  end

  let(:invalid_attributes) do
    skip('Add a hash of attributes invalid for your model')
  end

  describe 'GET /index' do
    it 'renders a successful response' do
      Reader.create! valid_attributes
      get readers_url
      expect(response).to be_successful
    end
  end

  describe 'GET /show' do
    it 'renders a successful response' do
      reader = Reader.create! valid_attributes
      get reader_url(reader)
      expect(response).to be_successful
    end
  end

  describe 'GET /new' do
    it 'renders a successful response' do
      get new_reader_url
      expect(response).to be_successful
    end
  end

  describe 'GET /edit' do
    it 'renders a successful response' do
      reader = Reader.create! valid_attributes
      get edit_reader_url(reader)
      expect(response).to be_successful
    end
  end

  describe 'POST /create' do
    context 'with valid parameters' do
      it 'creates a new Reader' do
        expect do
          post readers_url, params: { reader: valid_attributes }
        end.to change(Reader, :count).by(1)
      end

      it 'redirects to the created reader' do
        post readers_url, params: { reader: valid_attributes }
        expect(response).to redirect_to(reader_url(Reader.last))
      end
    end

    context 'with invalid parameters' do
      it 'does not create a new Reader' do
        expect do
          post readers_url, params: { reader: invalid_attributes }
        end.to change(Reader, :count).by(0)
      end

      it "renders a response with 422 status (i.e. to display the 'new' template)" do
        post readers_url, params: { reader: invalid_attributes }
        expect(response).to have_http_status(:unprocessable_entity)
      end
    end
  end

  describe 'PATCH /update' do
    context 'with valid parameters' do
      let(:new_attributes) do
        skip('Add a hash of attributes valid for your model')
      end

      it 'updates the requested reader' do
        reader = Reader.create! valid_attributes
        patch reader_url(reader), params: { reader: new_attributes }
        reader.reload
        skip('Add assertions for updated state')
      end

      it 'redirects to the reader' do
        reader = Reader.create! valid_attributes
        patch reader_url(reader), params: { reader: new_attributes }
        reader.reload
        expect(response).to redirect_to(reader_url(reader))
      end
    end

    context 'with invalid parameters' do
      it "renders a response with 422 status (i.e. to display the 'edit' template)" do
        reader = Reader.create! valid_attributes
        patch reader_url(reader), params: { reader: invalid_attributes }
        expect(response).to have_http_status(:unprocessable_entity)
      end
    end
  end

  describe 'DELETE /destroy' do
    it 'destroys the requested reader' do
      reader = Reader.create! valid_attributes
      expect do
        delete reader_url(reader)
      end.to change(Reader, :count).by(-1)
    end

    it 'redirects to the readers list' do
      reader = Reader.create! valid_attributes
      delete reader_url(reader)
      expect(response).to redirect_to(readers_url)
    end
  end
end
